# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LittleBee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LittleBee
pod ‘AFNetworking’
pod 'JASidePanels'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'YYModel'
pod 'Reachability'
end
